### PR TITLE
Show the header when printing to stdout as well

### LINKED ISSUE #331: hpack doesn't create hash header when told to print to stdout
Use case:

* docker with project mounted read-only into the container
* shake has a rule to create the project .cabal file by running the container and writing the stdout result to the .cabal file on the host (because stack is automagic and doesn't let you control anything, e.g. how hpack is invoked)

Except, this doesn't work, because the hpack header is missing, resulting in the host stack to complain about a modified .cabal file all the time.

Why is the header missing? Is there a reason?

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #331

### CODE REVIEW

File: src/Hpack.hs [hunk 1]
```diff
@@ -181,9 +181,10 @@ hpackResultWithVersion v (Options options force toStdout) = do
   case status of
     Generated -> do
       let hash = sha256 withoutHeader
+          out  = cabalVersion ++ header (decodeOptionsTarget options) v hash ++ body
       if toStdout
```
Comment (ip1981) [inline src/Hpack.hs]: No reason to keep this.

**Comment by sol** [comment]
Thanks a lot!

**Comment by sol** [comment]
Released to Hackage as `0.31.1`.
